# Cargo configuration for better profiling support

[build]
# Force frame pointers for accurate stack unwinding in heap profiling
rustflags = ["-C", "force-frame-pointers=yes"]

[env]
# Enable jemalloc profiling at build time
# This tells tikv-jemalloc-sys to compile jemalloc with profiling support
JEMALLOC_SYS_WITH_MALLOC_CONF = "prof:true"
